service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: personalAccount
  region: us-east-1

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: product-list
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: product-list/{id}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
