service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: personalAccount
  region: us-east-1
  environment:
    PG_HOST: ''
    PG_PORT: ''
    PG_DB: ''
    PG_USERNAME: ''
    PG_PASSWORD: ''

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          method: get
          path: product-list
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          method: get
          path: product-list/{id}
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          method: post
          path: product-list

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
